name: Build XRay
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Setup Android SDK/NDK and CMake
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          ndk: 27.2.12479018
          cmake: '3.22.1'

      - name: Build
        env:
          ANDROID_NDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}/ndk/27.2.12479018
        run: |
          xmake f -p android -a arm64-v8a -m release --ndk="$ANDROID_NDK_ROOT" --ndk_sdkver=33
          xmake -y

      - uses: actions/upload-artifact@v4
        with:
          name: XRay-arm64
          path: build/**/XRay.so
